/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardVerifyRouteImport } from './routes/dashboard/verify'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRevokeRouteImport } from './routes/dashboard/revoke'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard/records'
import { Route as DashboardMintRouteImport } from './routes/dashboard/mint'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiFilesCidRouteImport } from './routes/api/files/$cid'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerifyRoute = DashboardVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevokeRoute = DashboardRevokeRouteImport.update({
  id: '/revoke',
  path: '/revoke',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMintRoute = DashboardMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesCidRoute = ApiFilesCidRouteImport.update({
  id: '/api/files/$cid',
  path: '/api/files/$cid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/verify': typeof VerifyRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/mint': typeof DashboardMintRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/revoke': typeof DashboardRevokeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/files/$cid': typeof ApiFilesCidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledger': typeof LedgerRoute
  '/verify': typeof VerifyRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/mint': typeof DashboardMintRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/revoke': typeof DashboardRevokeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/files/$cid': typeof ApiFilesCidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/verify': typeof VerifyRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/mint': typeof DashboardMintRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/revoke': typeof DashboardRevokeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/files/$cid': typeof ApiFilesCidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/ledger'
    | '/verify'
    | '/api/upload'
    | '/dashboard/mint'
    | '/dashboard/records'
    | '/dashboard/revoke'
    | '/dashboard/settings'
    | '/dashboard/verify'
    | '/dashboard/'
    | '/api/files/$cid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ledger'
    | '/verify'
    | '/api/upload'
    | '/dashboard/mint'
    | '/dashboard/records'
    | '/dashboard/revoke'
    | '/dashboard/settings'
    | '/dashboard/verify'
    | '/dashboard'
    | '/api/files/$cid'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/ledger'
    | '/verify'
    | '/api/upload'
    | '/dashboard/mint'
    | '/dashboard/records'
    | '/dashboard/revoke'
    | '/dashboard/settings'
    | '/dashboard/verify'
    | '/dashboard/'
    | '/api/files/$cid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LedgerRoute: typeof LedgerRoute
  VerifyRoute: typeof VerifyRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiFilesCidRoute: typeof ApiFilesCidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verify': {
      id: '/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof DashboardVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revoke': {
      id: '/dashboard/revoke'
      path: '/revoke'
      fullPath: '/dashboard/revoke'
      preLoaderRoute: typeof DashboardRevokeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mint': {
      id: '/dashboard/mint'
      path: '/mint'
      fullPath: '/dashboard/mint'
      preLoaderRoute: typeof DashboardMintRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$cid': {
      id: '/api/files/$cid'
      path: '/api/files/$cid'
      fullPath: '/api/files/$cid'
      preLoaderRoute: typeof ApiFilesCidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardMintRoute: typeof DashboardMintRoute
  DashboardRecordsRoute: typeof DashboardRecordsRoute
  DashboardRevokeRoute: typeof DashboardRevokeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVerifyRoute: typeof DashboardVerifyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMintRoute: DashboardMintRoute,
  DashboardRecordsRoute: DashboardRecordsRoute,
  DashboardRevokeRoute: DashboardRevokeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVerifyRoute: DashboardVerifyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LedgerRoute: LedgerRoute,
  VerifyRoute: VerifyRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiFilesCidRoute: ApiFilesCidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
